import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TailwindCSS - Practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="https://cdn.hugeicons.com/icons/code-stroke-rounded.svg" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}